// Routes are automatically generated by unplugin-vue-router from src/pages/
// Router is created in main.ts via vue-router/auto-routes
// This file is no longer needed but kept as a reference
export {}
