/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgendaCard: typeof import('./features/agenda/components/AgendaCard.vue')['default']
    AgendaPreview: typeof import('./features/home/components/AgendaPreview.vue')['default']
    AlertBanner: typeof import('./shared/components/ui/AlertBanner.vue')['default']
    AppSection: typeof import('./shared/components/layout/AppSection.vue')['default']
    AuthModal: typeof import('./shared/components/ui/AuthModal.vue')['default']
    AvailabilityBadge: typeof import('./features/agenda/components/AvailabilityBadge.vue')['default']
    BaseArrowLink: typeof import('./shared/components/ui/BaseArrowLink.vue')['default']
    BaseBadge: typeof import('./shared/components/ui/BaseBadge.vue')['default']
    BaseButton: typeof import('./shared/components/ui/BaseButton.vue')['default']
    BaseCard: typeof import('./shared/components/ui/BaseCard.vue')['default']
    BaseDialog: typeof import('./shared/components/ui/BaseDialog.vue')['default']
    BaseFormField: typeof import('./shared/components/ui/BaseFormField.vue')['default']
    BaseImage: typeof import('./shared/components/ui/BaseImage.vue')['default']
    BasePagination: typeof import('./shared/components/ui/BasePagination.vue')['default']
    BaseSkeleton: typeof import('./shared/components/ui/BaseSkeleton.vue')['default']
    BlogCard: typeof import('./features/blog/components/BlogCard.vue')['default']
    BoardCard: typeof import('./features/board/components/BoardCard.vue')['default']
    CtaBlock: typeof import('./shared/components/CtaBlock.vue')['default']
    EmptyState: typeof import('./shared/components/ui/EmptyState.vue')['default']
    ErrorState: typeof import('./shared/components/ui/ErrorState.vue')['default']
    FaqAccordion: typeof import('./shared/components/ui/FaqAccordion.vue')['default']
    HeroVideo: typeof import('./features/home/components/HeroVideo.vue')['default']
    IconFacebook: typeof import('./shared/components/layout/IconFacebook.vue')['default']
    IconInstagram: typeof import('./shared/components/layout/IconInstagram.vue')['default']
    IDealFlow: typeof import('./features/steunen/components/IDealFlow.vue')['default']
    MissionBlock: typeof import('./features/home/components/MissionBlock.vue')['default']
    PageHero: typeof import('./shared/components/layout/PageHero.vue')['default']
    PhotoGrid: typeof import('./shared/components/ui/PhotoGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SanitizedHtml: typeof import('./shared/components/ui/SanitizedHtml.vue')['default']
    SectionHeader: typeof import('./shared/components/ui/SectionHeader.vue')['default']
    SidebarLayout: typeof import('./shared/components/layout/SidebarLayout.vue')['default']
    SkipToMain: typeof import('./shared/components/layout/SkipToMain.vue')['default']
    SponsorGrid: typeof import('./features/home/components/SponsorGrid.vue')['default']
    StatsBar: typeof import('./features/home/components/StatsBar.vue')['default']
    SupportBlock: typeof import('./features/steunen/components/SupportBlock.vue')['default']
    TestimonialBlock: typeof import('./features/home/components/TestimonialBlock.vue')['default']
    TextImageBlock: typeof import('./shared/components/TextImageBlock.vue')['default']
    TheFooter: typeof import('./shared/components/layout/TheFooter.vue')['default']
    TheHeader: typeof import('./shared/components/layout/TheHeader.vue')['default']
    ThemeToggle: typeof import('./shared/components/layout/ThemeToggle.vue')['default']
    TheTopBar: typeof import('./shared/components/layout/TheTopBar.vue')['default']
    WhySWG: typeof import('./features/home/components/WhySWG.vue')['default']
  }
}
